### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by The-UltimateGamer** [The-UltimateGamer/GUIdo#4]
## THIS WILL NEVER BE CLOSED
This is the GUIdo chat issue, for devs to talk... I guess?

**Comment by The-UltimateGamer** [comment]
Hello World!

**Comment by pythonleo** [comment]
yeah im here

**Comment by pythonleo** [comment]
okay i actually have a few ideas for today

**Comment by pythonleo** [comment]
i think we should start doing btns with text

**Comment by The-UltimateGamer** [comment]
yeah

**Comment by The-UltimateGamer** [comment]
im thinkin about a cmd-line text editor w/ c++

**Comment by The-UltimateGamer** [comment]
i have this whole scheme for the cmd now

**Comment by The-UltimateGamer** [comment]
it's a real program, and it feeds the cmd in the "OS"

**Comment by The-UltimateGamer** [comment]
kinda like doing a `freopen` to the screen

**Comment by The-UltimateGamer** [comment]
in fact i already have a prototype

**Comment by pythonleo** [comment]
okay...

**Comment by pythonleo** [comment]
well im gonna do the btn thing

**Comment by The-UltimateGamer** [comment]
and u can do the txt rendering

**Comment by The-UltimateGamer** [comment]
yep

**Comment by The-UltimateGamer** [comment]
much like the `ed` editor on unix

**Comment by The-UltimateGamer** [comment]
AND we will be doing a GUI txt editor

**Comment by The-UltimateGamer** [comment]
wht should i call the cmd one

**Comment by pythonleo** [comment]
*vis* for Vi Simplified(?)

**Comment by The-UltimateGamer** [comment]
but ed

**Comment by The-UltimateGamer** [comment]
like more primitive than visssssssss

**Comment by The-UltimateGamer** [comment]
~~eddie?~~

**Comment by pythonleo** [comment]
..........

**Comment by The-UltimateGamer** [comment]
yeah can we really call it eddie?

**Comment by The-UltimateGamer** [comment]
not sure tho

**Comment by pythonleo** [comment]
just..dont

**Comment by The-UltimateGamer** [comment]
well fine

**Comment by The-UltimateGamer** [comment]
another name

**Comment by The-UltimateGamer** [comment]
nvm just `vis`

**Comment by pythonleo** [comment]
![image](https://user-images.githubusercontent.com/31534391/84569475-744d4f00-adb9-11ea-9c5f-9070be687022.png)
okay got the bg done

**Comment by pythonleo** [comment]
heck githubusercontent is still blocked

**Comment by The-UltimateGamer** [comment]
ohh

**Comment by pythonleo** [comment]
![image](https://user-images.githubusercontent.com/31534391/84569726-4c5eeb00-adbb-11ea-92ee-ed498ed5b3a6.png)
![image](https://user-images.githubusercontent.com/31534391/84569757-6e586d80-adbb-11ea-8afc-f9e16370f179.png)
ohhhhhhhhhhh

**Comment by pythonleo** [comment]
(there's no text yet but still)

**Comment by The-UltimateGamer** [comment]
ohhhhh

**Comment by The-UltimateGamer** [comment]
amazing

**Comment by The-UltimateGamer** [comment]
vis is almost done

**Comment by pythonleo** [comment]
okay

**Comment by The-UltimateGamer** [comment]
check it out:
```cpp
#include <cstdio>

void write(); //Accepts text input from user

int main(int argc, char** argv)
{
	if (!argv[1])
	{
		printf("Missing argument.\nUsage: vis <filename>")
		return 0;
	}
	while (true)
	{
		char* cmd;
		scanf("%s", &cmd);
		if (cmd == "w")
		{
			freopen(argv[1], "w", stdout);
			write();
		}
		else if (cmd == "a")
		{
			freopen(argv[1], "a", stdout);
			write();
		}
	}
}

void write()
{
	while (true)
	{
		char* line;
		gets(line);
		printf("%s", line);
		if (line == ".")
		{
			#ifdef _WIN32
				freopen("con", "w", stdout);
			#elif defined __unix__
				freopen("/dev/tty", "w", stdout);
			#endif
			break;
		}
	}
}
```

**Comment by The-UltimateGamer** [comment]
`printf("Missing argument.\nUsage: vis <filename>")` missing `;`
add that

**Comment by pythonleo** [comment]
ohhh

**Comment by pythonleo** [comment]
nice

**Comment by The-UltimateGamer** [comment]
damn

**Comment by The-UltimateGamer** [comment]
didnt work
debugging

**Comment by pythonleo** [comment]
me too lol

**Comment by pythonleo** [comment]
btw whats the `c` arg in `Txt`

**Comment by pythonleo** [comment]
btw whats the `c` arg in `Txt`

**Comment by The-UltimateGamer** [comment]
color

**Comment by pythonleo** [comment]
oh

**Comment by pythonleo** [comment]
![image](https://user-images.githubusercontent.com/31534391/84570009-060a8b80-adbd-11ea-93bd-4e67813ef99b.png)
![image](https://user-images.githubusercontent.com/31534391/84570017-128ee400-adbd-11ea-805e-3b255f6a4575.png)
omg it worked!!!

**Comment by The-UltimateGamer** [comment]
# OMG!!!

**Comment by The-UltimateGamer** [comment]
now slap on the fixedsys font

**Comment by The-UltimateGamer** [comment]
# VIS WORKED!!!

**Comment by The-UltimateGamer** [comment]
```cpp
#include <iostream>
#include <string>

void write(); //Accepts text input from user

int main(int argc, char** argv)
{
	if (!argv[1])
	{
		printf("Missing argument.\nUsage: vis <filename>");
		return 0;
	}
	while (true)
	{
		std::string cmd;
		std::cin >> cmd;
		if (cmd == "i")
		{
			freopen(argv[1], "w", stdout);
			write();
		}
		else if (cmd == "a")
		{
			freopen(argv[1], "a", stdout);
			write();
		}
		else if (cmd == "q")
			return 0;
		else
			printf("?\n");
	}
}

void write()
{
	while (true)
	{
		std::string line;
		std::getline(std::cin, line);
		if (line == ".")
		{
			#ifdef _WIN32
				freopen("con", "w", stdout);
			#elif defined __unix__
				freopen("/dev/tty", "w", stdout);
			#endif
			break;
		}
		std::cout << line << std::endl;
	}
}
```

**Comment by The-UltimateGamer** [comment]
Let's commit that and call it a day, shall we

**Comment by The-UltimateGamer** [comment]
Go ahead and do a pull req

**Comment by pythonleo** [comment]
yeah im done too

**Comment by pythonleo** [comment]
go on & merge

**Comment by pythonleo** [comment]
im going offline

**Comment by pythonleo** [comment]
![image](https://user-images.githubusercontent.com/31534391/84966672-a3aae580-b144-11ea-8f40-461af21975f9.png)
![image](https://user-images.githubusercontent.com/31534391/84966676-a73e6c80-b144-11ea-94b0-37d1d165ff07.png)
got a few better images from classic theme windows 7, gonna gimp them when im free

**Comment by The-UltimateGamer** [comment]
let's try to make our own OS logo&nbsp;&nbsp;
this is fine tho




------------------&nbsp;Original&nbsp;------------------

**Comment by pythonleo** [comment]
yeah...but i cant think of a cool design
btw can we move the dev session today to next wed, i gotta review stuff

**Comment by The-UltimateGamer** [comment]
Fine then


------------------ Original ------------------

**Comment by pythonleo** [comment]
gosh i finally scrolled down
***WHY DOES GITHUB LAZYLOAD!!!***

**Comment by The-UltimateGamer** [comment]
well yeah...



------------------&nbsp;Original&nbsp;------------------

**Comment by pythonleo** [comment]
well anyways
im gonna say up front
i made a few tweaks to the text btn thing, gotta push them over

**Comment by The-UltimateGamer** [comment]
ok

**Comment by The-UltimateGamer** [comment]
i might as well tell u about the file system

**Comment by The-UltimateGamer** [comment]
Each program is like this:
```plain
<NAME><LOC><SIZE_IN_BYTES><CONTENT>
```

**Comment by The-UltimateGamer** [comment]
And we stuff all of these in one img file

**Comment by pythonleo** [comment]
...yeah?

**Comment by The-UltimateGamer** [comment]
basically, and using the all-powerful `eval()` to do that

**Comment by The-UltimateGamer** [comment]
![image](https://user-images.githubusercontent.com/40680747/85921272-babca680-b8ad-11ea-9842-e78b654631b9.png)

**Comment by pythonleo** [comment]
...yeah i know eval

**Comment by pythonleo** [comment]
so just execute the content?

**Comment by The-UltimateGamer** [comment]
wait

**Comment by The-UltimateGamer** [comment]
it's actually `exec()` that we need
![image](https://user-images.githubusercontent.com/40680747/85921326-256de200-b8ae-11ea-8def-11de1bb56c26.png)

**Comment by The-UltimateGamer** [comment]
`eval()` cant do complex stuff
that would be an error if we used `eval()`

**Comment by The-UltimateGamer** [comment]
done

**Comment by The-UltimateGamer** [comment]
lemme reboot into ubuntu
i need hexedit

**Comment by The-UltimateGamer** [comment]
one moment

**Comment by pythonleo** [comment]
yeah okay

**Comment by pythonleo** [comment]
btw `eval()` returns the value while `exec()` doesnt

**Comment by pythonleo** [comment]
keep that in mind

**Comment by pythonleo** [comment]
![image](https://user-images.githubusercontent.com/31534391/85921377-957c6800-b8ae-11ea-8937-8d7b96f808ad.png)

**Comment by The-UltimateGamer** [comment]
eval to eval equations and stuff
exec to do code

**Comment by The-UltimateGamer** [comment]
guess i should start with `stub`

**Comment by The-UltimateGamer** [comment]
STUB: STUB The Unique Bootloader

**Comment by pythonleo** [comment]
well yeah

**Comment by pythonleo** [comment]
so what do i do

**Comment by The-UltimateGamer** [comment]
lemme think

**Comment by The-UltimateGamer** [comment]
start guiding the buttons

**Comment by The-UltimateGamer** [comment]
tying Guide to them

**Comment by The-UltimateGamer** [comment]
and actually going places

**Comment by The-UltimateGamer** [comment]
from now on every "app" is gonna be fullscreen

**Comment by The-UltimateGamer** [comment]
AND only singletasking

**Comment by pythonleo** [comment]
okay

**Comment by The-UltimateGamer** [comment]
let's attempt at least that

**Comment by pythonleo** [comment]
start simple

**Comment by The-UltimateGamer** [comment]
yeah

**Comment by pythonleo** [comment]
and btw u do know that in python 3 u don't have to extend from `object`, don't you

**Comment by The-UltimateGamer** [comment]
well didnt know that

**Comment by The-UltimateGamer** [comment]
well nvm about that

**Comment by The-UltimateGamer** [comment]
btw what should the header be?

**Comment by pythonleo** [comment]
hmm

**Comment by The-UltimateGamer** [comment]
could be a hint to the devs...

**Comment by The-UltimateGamer** [comment]
`WORKOFKEVTUGANDTECHYLEO`?

**Comment by pythonleo** [comment]
That...is not much of a *hint*, more like a *message*

**Comment by The-UltimateGamer** [comment]
well implicit

**Comment by The-UltimateGamer** [comment]
btw i need a name 4 the img file

**Comment by pythonleo** [comment]
well jus' call it `files.img` or sth

**Comment by The-UltimateGamer** [comment]
well fine

**Comment by The-UltimateGamer** [comment]
i need a header tho

**Comment by pythonleo** [comment]
yeah...

**Comment by pythonleo** [comment]
how about this
`LICENSED UNDER THE AGPL & KTUGPL`

**Comment by The-UltimateGamer** [comment]
KTUGPL?

**Comment by pythonleo** [comment]
cuz ur `K(ev)TUG` and im `P(ython)L(eo)`

**Comment by The-UltimateGamer** [comment]
ahh

**Comment by The-UltimateGamer** [comment]
NICE

**Comment by The-UltimateGamer** [comment]
im gonna strip the spaces

**Comment by The-UltimateGamer** [comment]
`LICENSEDUNDERTHEAGPL&KTUGPL`

**Comment by The-UltimateGamer** [comment]
even better, `LICENSEDUNDERAGPL&KTUGPL`
nice & unreadable

**Comment by pythonleo** [comment]
yeah well play with it as u like

**Comment by The-UltimateGamer** [comment]
so we separate programs w/ the NUL char

**Comment by pythonleo** [comment]
well i got my part done

**Comment by The-UltimateGamer** [comment]
ohh

**Comment by The-UltimateGamer** [comment]
lemme see

**Comment by The-UltimateGamer** [comment]
btw lemme go and get some water

**Comment by The-UltimateGamer** [comment]
stub's done 2

**Comment by The-UltimateGamer** [comment]
it's already an hr

**Comment by The-UltimateGamer** [comment]
let's just call it a day

**Comment by The-UltimateGamer** [comment]
lemme push that

**Comment by The-UltimateGamer** [comment]
im off

**Comment by The-UltimateGamer** [comment]
```plain
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
```

**Comment by The-UltimateGamer** [comment]
![image](https://user-images.githubusercontent.com/40680747/87245883-d31aec80-c47b-11ea-9efd-b5ba58cc8736.png)

**Comment by The-UltimateGamer** [comment]
![image](https://user-images.githubusercontent.com/40680747/87245994-b92dd980-c47c-11ea-87b4-09aa1b39e47b.png)

**Comment by The-UltimateGamer** [comment]
```plain
LICENSEDUNDERAGPL&KTUGPL.PROGRAM_NAME DIR CODE.[OTHER PROGRAMS]
```
. = NUL / '\0'

**Comment by The-UltimateGamer** [comment]
![image](https://user-images.githubusercontent.com/40680747/87246147-ec249d00-c47d-11ea-8ef5-6c82239b73b6.png)

**Comment by The-UltimateGamer** [comment]
![image](https://user-images.githubusercontent.com/40680747/87246472-4e7e9d00-c480-11ea-893e-9765402ee637.png)

**Comment by pythonleo** [comment]
#TheRubbishDocsOfPygame

**Comment by The-UltimateGamer** [comment]
makes sense

**Comment by pythonleo** [comment]
o...kay i am here

**Comment by pythonleo** [comment]
so i'm supposed to make `stub` the bootloader actually boot

**Comment by pythonleo** [comment]
okay im done LOL

**Comment by The-UltimateGamer** [comment]
quick
Btw im back
Just a sec

------------------ Original ------------------

**Comment by The-UltimateGamer** [comment]
`ls`, `rm`, `cd`, `vis`, `cat`

**Comment by The-UltimateGamer** [comment]
### Virtual Disk Specification
Each program is written into the disk as follows:
`[LOC] [PROGRAM]`

**Comment by The-UltimateGamer** [comment]
> size isnt everything
> -Linus Tips

**Comment by The-UltimateGamer** [comment]
![image](https://user-images.githubusercontent.com/40680747/88456976-4f1e2700-ceb5-11ea-9b2a-1ccc8df1680d.png)

**Comment by The-UltimateGamer** [comment]
commands: `/bin`

**Comment by pythonleo** [comment]
https://devdocs.io/pygame/

**Comment by The-UltimateGamer** [comment]
`[LOC]\a[PROGRAM]`

**Comment by pythonleo** [comment]
```
!LOC:/sys/
!FNAME:kernel.py
# content
```

**Comment by The-UltimateGamer** [comment]
```
!LOC=/sys/
!FNAME=kernel.py
# content```

**Comment by pythonleo** [comment]
Me: Mom can we have stub?
Mom: We have stub at home
stub at home:
![image](https://user-images.githubusercontent.com/31534391/88458018-7b3da600-cebd-11ea-95f9-f31ea6d22dc5.png)

**Comment by pythonleo** [comment]
(and no boot)

**Comment by pythonleo** [comment]
```
"""
The `pwd` command
Prints the current working directory
"""

def pwd(working_dir):
	print(working_dir)
```

**Comment by The-UltimateGamer** [comment]
*sys*

**Comment by The-UltimateGamer** [comment]
`/` and `~`

**Comment by pythonleo** [comment]
```
# The `cat` command
# Shows the contents of a given file (in pure text)
# Only works when file is in pwd (for now)

def cat(working_dir, *args):
	if not args:
		print("Missing argument.\nUsage: cat <filename(s)>")
		return
	for target in args:
		files = open("files.img", 'r+')
		lines = files.read().strip('\0').split('\n')
		contents = []
		for i, line in enumerate(lines):
			if line == '!LOC=%s' % working_dir\
		   and lines[i+1] == '!FNAME=%s' % target:
				for i in range(i+2, len(lines)):
					if lines[i] and lines[i][0] == '!': break
					contents.append(lines[i])
				break
		else:
			print("File not found: %s" % target)
		print('\n'.join(contents))
		files.close()
```

**Comment by The-UltimateGamer** [comment]
![image](https://user-images.githubusercontent.com/40680747/89123018-b6178d80-d4fe-11ea-9154-98b7534f688f.png)

**Comment by pythonleo** [comment]
```
# The `ls` command
# Shows all files in pwd

def ls(working_dir, *args):
	files = open("files.img", 'r+')
	lines = files.read().strip('\0').split('\n')
	for i, line in enumerate(lines):
		if line == "!LOC=%s" % working_dir:
			print(lines[i+1].strip('!FNAME='))
```

**Comment by The-UltimateGamer** [comment]
![image](https://user-images.githubusercontent.com/40680747/89123126-85842380-d4ff-11ea-96bf-c1cb7b279fe6.png)

**Comment by The-UltimateGamer** [comment]
![image](https://user-images.githubusercontent.com/40680747/89123206-35f22780-d500-11ea-9d18-ff86bcf2679d.png)

**Comment by The-UltimateGamer** [comment]
![image](https://user-images.githubusercontent.com/40680747/89123304-ee1fd000-d500-11ea-997a-7aad8e41f7ea.png)

**Comment by The-UltimateGamer** [comment]
![image](https://user-images.githubusercontent.com/40680747/89123318-0394fa00-d501-11ea-91b1-5d82b5e1c990.png)

**Comment by pythonleo** [comment]
```
# The `rm` command
# Removes a file in pwd (hopefully)

def rm(working_dir, *args):
	files = open("files.img", 'r+')
	to_be_written = []
	target = args[0]
	lines = files.read().strip('\0').split('\n')
	write_or_not = True
	for i, line in enumerate(lines):
		if write_or_not:
			if line == '!FNAME=%s' % target\
		   and lines[i-1] == '!LOC=%s' % working_dir:
				write_or_not = False
		else:
			if line and line[0] == '!':
				write_or_not = True
		if write_or_not:
			to_be_written.append(line)
	files.close()
	fw = open("files.img", 'w+')
	fw.write('\n'.join(to_be_written))
	fw.close()
```

**Comment by pythonleo** [comment]
```
# The `rm` command
# Removes a file in pwd (hopefully)

def rm(working_dir, *args):
	files = open("files.img", 'r+')
	to_be_written = []
	target = args[0]
	lines = files.read().strip('\0').split('\n')
	write_or_not = True
	for i, line in enumerate(lines):
		if write_or_not:
			if line == '!FNAME=%s' % target\
		   and lines[i-1] == '!LOC=%s' % working_dir:
				write_or_not = False
				del to_be_written[-1]
		else:
			if line and line[0] == '!':
				write_or_not = True
		if write_or_not:
			to_be_written.append(line)
	files.close()
	fw = open("files.img", 'w+')
	fw.write('\n'.join(to_be_written))
	fw.close()
```

**Comment by pythonleo** [comment]
```
# Our "scriptable calculator"
# Calculates an expression
# Enter q to quit

def calc(working_dir, *args):    # arguments are completely unused
	expr = input()
	while expr != 'q':
		print(eval(expr))
		expr = input()
```

**Comment by The-UltimateGamer** [comment]
`from math import *`

**Comment by The-UltimateGamer** [comment]
`(math.)sin(30)`

**Comment by The-UltimateGamer** [comment]
*Winnux 58*

**Comment by The-UltimateGamer** [comment]
![image](https://user-images.githubusercontent.com/40680747/89730844-0ea5d800-da75-11ea-8238-eaa087ad260f.png)

**Comment by The-UltimateGamer** [comment]
> soviet vibes

**Comment by The-UltimateGamer** [comment]
![image](https://user-images.githubusercontent.com/40680747/89731234-ef5c7a00-da77-11ea-812e-f6161fcdc714.png)

**Comment by The-UltimateGamer** [comment]
![image](https://user-images.githubusercontent.com/40680747/89731257-1e72eb80-da78-11ea-977b-95f4b13e5a15.png)

**Comment by pythonleo** [comment]
![image](https://user-images.githubusercontent.com/31534391/90333350-af594200-dff7-11ea-9997-08b4168c98d9.png)
![image](https://user-images.githubusercontent.com/31534391/90333354-b6805000-dff7-11ea-981f-77d903bdeed1.png)

**Comment by The-UltimateGamer** [comment]
`a = var + "/"`
`a += "..."`

**Comment by The-UltimateGamer** [comment]
`str(a + "/")`

**Comment by pythonleo** [comment]
![image](https://user-images.githubusercontent.com/31534391/90333546-55f21280-dff9-11ea-95a3-0ca7667fc509.png)
![image](https://user-images.githubusercontent.com/31534391/90333550-61453e00-dff9-11ea-98f9-c5dd092f4882.png)

**Comment by pythonleo** [comment]
![image](https://user-images.githubusercontent.com/31534391/90333964-b5055680-dffc-11ea-8b23-1c3a7b5be002.png)

**Comment by The-UltimateGamer** [comment]
/sys/etc/

**Comment by The-UltimateGamer** [comment]
etc/a.txt

**Comment by pythonleo** [comment]
```
!LOC=/sys/
!FNAME=etc
......
!LOC=/sts/etc/
!FNAME=a.txt
```

**Comment by The-UltimateGamer** [comment]
![image](https://user-images.githubusercontent.com/40680747/90334476-71145080-e000-11ea-8eae-ff5598349728.png)

**Comment by The-UltimateGamer** [comment]
`!LOC=/a/b/c`
`/a$ ls`
output?

**Comment by The-UltimateGamer** [comment]
b/c

**Comment by The-UltimateGamer** [comment]
bye chat
had fun
